// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: lider.proto

package lider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player   int64  `protobuf:"varint,1,opt,name=player,proto3" json:"player,omitempty"`    // player id
	Play     int64  `protobuf:"varint,2,opt,name=play,proto3" json:"play,omitempty"`        // content of the move
	Response string `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"` // response to the move
}

func (x *Interaction) Reset() {
	*x = Interaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interaction) ProtoMessage() {}

func (x *Interaction) ProtoReflect() protoreflect.Message {
	mi := &file_lider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interaction.ProtoReflect.Descriptor instead.
func (*Interaction) Descriptor() ([]byte, []int) {
	return file_lider_proto_rawDescGZIP(), []int{0}
}

func (x *Interaction) GetPlayer() int64 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *Interaction) GetPlay() int64 {
	if x != nil {
		return x.Play
	}
	return 0
}

func (x *Interaction) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type PlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`     // type of request. 0: connection, 1: send move
	Player int32 `protobuf:"varint,2,opt,name=player,proto3" json:"player,omitempty"` // player id
	Play   int32 `protobuf:"varint,3,opt,name=play,proto3" json:"play,omitempty"`     // content of the play
	Round  int32 `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`   // round number
	Total  int32 `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *PlayerRequest) Reset() {
	*x = PlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRequest) ProtoMessage() {}

func (x *PlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRequest.ProtoReflect.Descriptor instead.
func (*PlayerRequest) Descriptor() ([]byte, []int) {
	return file_lider_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PlayerRequest) GetPlayer() int32 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *PlayerRequest) GetPlay() int32 {
	if x != nil {
		return x.Play
	}
	return 0
}

func (x *PlayerRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *PlayerRequest) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`         // type of response. 0: init game round, 1: result of the move
	Player   int32 `protobuf:"varint,2,opt,name=player,proto3" json:"player,omitempty"`     // player id
	Response int32 `protobuf:"varint,3,opt,name=response,proto3" json:"response,omitempty"` // content of the play
	Round    int32 `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`       //round
}

func (x *PlayerResponse) Reset() {
	*x = PlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResponse) ProtoMessage() {}

func (x *PlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResponse.ProtoReflect.Descriptor instead.
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return file_lider_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PlayerResponse) GetPlayer() int32 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *PlayerResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

func (x *PlayerResponse) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

var File_lider_proto protoreflect.FileDescriptor

var file_lider_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x69, 0x64, 0x65, 0x72, 0x22, 0x55, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7b, 0x0a, 0x0d, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x6e, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x89, 0x03, 0x0a, 0x0d, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0d, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x6c, 0x69,
	0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x40,
	0x0a, 0x0b, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x14, 0x2e,
	0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x3c, 0x0a, 0x07, 0x46, 0x61, 0x73, 0x65, 0x31, 0x50, 0x31, 0x12, 0x14, 0x2e, 0x6c, 0x69,
	0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3c,
	0x0a, 0x07, 0x46, 0x61, 0x73, 0x65, 0x31, 0x50, 0x32, 0x12, 0x14, 0x2e, 0x6c, 0x69, 0x64, 0x65,
	0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x05,
	0x46, 0x61, 0x73, 0x65, 0x32, 0x12, 0x14, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x69,
	0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x05, 0x46, 0x61, 0x73, 0x65,
	0x33, 0x12, 0x14, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x4c, 0x61, 0x62, 0x32, 0x5f, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f, 0x73, 0x2f, 0x73, 0x71, 0x75, 0x69, 0x64, 0x5f,
	0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_lider_proto_rawDescOnce sync.Once
	file_lider_proto_rawDescData = file_lider_proto_rawDesc
)

func file_lider_proto_rawDescGZIP() []byte {
	file_lider_proto_rawDescOnce.Do(func() {
		file_lider_proto_rawDescData = protoimpl.X.CompressGZIP(file_lider_proto_rawDescData)
	})
	return file_lider_proto_rawDescData
}

var file_lider_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lider_proto_goTypes = []interface{}{
	(*Interaction)(nil),    // 0: lider.Interaction
	(*PlayerRequest)(nil),  // 1: lider.PlayerRequest
	(*PlayerResponse)(nil), // 2: lider.PlayerResponse
}
var file_lider_proto_depIdxs = []int32{
	1, // 0: lider.PlayerService.PlayerHandler:input_type -> lider.PlayerRequest
	1, // 1: lider.PlayerService.WaitingRoom:input_type -> lider.PlayerRequest
	1, // 2: lider.PlayerService.Fase1P1:input_type -> lider.PlayerRequest
	1, // 3: lider.PlayerService.Fase1P2:input_type -> lider.PlayerRequest
	1, // 4: lider.PlayerService.Fase2:input_type -> lider.PlayerRequest
	1, // 5: lider.PlayerService.Fase3:input_type -> lider.PlayerRequest
	2, // 6: lider.PlayerService.PlayerHandler:output_type -> lider.PlayerResponse
	2, // 7: lider.PlayerService.WaitingRoom:output_type -> lider.PlayerResponse
	2, // 8: lider.PlayerService.Fase1P1:output_type -> lider.PlayerResponse
	2, // 9: lider.PlayerService.Fase1P2:output_type -> lider.PlayerResponse
	2, // 10: lider.PlayerService.Fase2:output_type -> lider.PlayerResponse
	2, // 11: lider.PlayerService.Fase3:output_type -> lider.PlayerResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lider_proto_init() }
func file_lider_proto_init() {
	if File_lider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lider_proto_goTypes,
		DependencyIndexes: file_lider_proto_depIdxs,
		MessageInfos:      file_lider_proto_msgTypes,
	}.Build()
	File_lider_proto = out.File
	file_lider_proto_rawDesc = nil
	file_lider_proto_goTypes = nil
	file_lider_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlayerServiceClient is the client API for PlayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerServiceClient interface {
	PlayerHandler(ctx context.Context, opts ...grpc.CallOption) (PlayerService_PlayerHandlerClient, error)
	WaitingRoom(ctx context.Context, opts ...grpc.CallOption) (PlayerService_WaitingRoomClient, error)
	Fase1P1(ctx context.Context, opts ...grpc.CallOption) (PlayerService_Fase1P1Client, error)
	Fase1P2(ctx context.Context, opts ...grpc.CallOption) (PlayerService_Fase1P2Client, error)
	Fase2(ctx context.Context, opts ...grpc.CallOption) (PlayerService_Fase2Client, error)
	Fase3(ctx context.Context, opts ...grpc.CallOption) (PlayerService_Fase3Client, error)
}

type playerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerServiceClient(cc grpc.ClientConnInterface) PlayerServiceClient {
	return &playerServiceClient{cc}
}

func (c *playerServiceClient) PlayerHandler(ctx context.Context, opts ...grpc.CallOption) (PlayerService_PlayerHandlerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PlayerService_serviceDesc.Streams[0], "/lider.PlayerService/PlayerHandler", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerServicePlayerHandlerClient{stream}
	return x, nil
}

type PlayerService_PlayerHandlerClient interface {
	Send(*PlayerRequest) error
	Recv() (*PlayerResponse, error)
	grpc.ClientStream
}

type playerServicePlayerHandlerClient struct {
	grpc.ClientStream
}

func (x *playerServicePlayerHandlerClient) Send(m *PlayerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playerServicePlayerHandlerClient) Recv() (*PlayerResponse, error) {
	m := new(PlayerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playerServiceClient) WaitingRoom(ctx context.Context, opts ...grpc.CallOption) (PlayerService_WaitingRoomClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PlayerService_serviceDesc.Streams[1], "/lider.PlayerService/WaitingRoom", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerServiceWaitingRoomClient{stream}
	return x, nil
}

type PlayerService_WaitingRoomClient interface {
	Send(*PlayerRequest) error
	Recv() (*PlayerResponse, error)
	grpc.ClientStream
}

type playerServiceWaitingRoomClient struct {
	grpc.ClientStream
}

func (x *playerServiceWaitingRoomClient) Send(m *PlayerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playerServiceWaitingRoomClient) Recv() (*PlayerResponse, error) {
	m := new(PlayerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playerServiceClient) Fase1P1(ctx context.Context, opts ...grpc.CallOption) (PlayerService_Fase1P1Client, error) {
	stream, err := c.cc.NewStream(ctx, &_PlayerService_serviceDesc.Streams[2], "/lider.PlayerService/Fase1P1", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerServiceFase1P1Client{stream}
	return x, nil
}

type PlayerService_Fase1P1Client interface {
	Send(*PlayerRequest) error
	Recv() (*PlayerResponse, error)
	grpc.ClientStream
}

type playerServiceFase1P1Client struct {
	grpc.ClientStream
}

func (x *playerServiceFase1P1Client) Send(m *PlayerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playerServiceFase1P1Client) Recv() (*PlayerResponse, error) {
	m := new(PlayerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playerServiceClient) Fase1P2(ctx context.Context, opts ...grpc.CallOption) (PlayerService_Fase1P2Client, error) {
	stream, err := c.cc.NewStream(ctx, &_PlayerService_serviceDesc.Streams[3], "/lider.PlayerService/Fase1P2", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerServiceFase1P2Client{stream}
	return x, nil
}

type PlayerService_Fase1P2Client interface {
	Send(*PlayerRequest) error
	Recv() (*PlayerResponse, error)
	grpc.ClientStream
}

type playerServiceFase1P2Client struct {
	grpc.ClientStream
}

func (x *playerServiceFase1P2Client) Send(m *PlayerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playerServiceFase1P2Client) Recv() (*PlayerResponse, error) {
	m := new(PlayerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playerServiceClient) Fase2(ctx context.Context, opts ...grpc.CallOption) (PlayerService_Fase2Client, error) {
	stream, err := c.cc.NewStream(ctx, &_PlayerService_serviceDesc.Streams[4], "/lider.PlayerService/Fase2", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerServiceFase2Client{stream}
	return x, nil
}

type PlayerService_Fase2Client interface {
	Send(*PlayerRequest) error
	Recv() (*PlayerResponse, error)
	grpc.ClientStream
}

type playerServiceFase2Client struct {
	grpc.ClientStream
}

func (x *playerServiceFase2Client) Send(m *PlayerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playerServiceFase2Client) Recv() (*PlayerResponse, error) {
	m := new(PlayerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playerServiceClient) Fase3(ctx context.Context, opts ...grpc.CallOption) (PlayerService_Fase3Client, error) {
	stream, err := c.cc.NewStream(ctx, &_PlayerService_serviceDesc.Streams[5], "/lider.PlayerService/Fase3", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerServiceFase3Client{stream}
	return x, nil
}

type PlayerService_Fase3Client interface {
	Send(*PlayerRequest) error
	Recv() (*PlayerResponse, error)
	grpc.ClientStream
}

type playerServiceFase3Client struct {
	grpc.ClientStream
}

func (x *playerServiceFase3Client) Send(m *PlayerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playerServiceFase3Client) Recv() (*PlayerResponse, error) {
	m := new(PlayerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PlayerServiceServer is the server API for PlayerService service.
type PlayerServiceServer interface {
	PlayerHandler(PlayerService_PlayerHandlerServer) error
	WaitingRoom(PlayerService_WaitingRoomServer) error
	Fase1P1(PlayerService_Fase1P1Server) error
	Fase1P2(PlayerService_Fase1P2Server) error
	Fase2(PlayerService_Fase2Server) error
	Fase3(PlayerService_Fase3Server) error
}

// UnimplementedPlayerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerServiceServer struct {
}

func (*UnimplementedPlayerServiceServer) PlayerHandler(PlayerService_PlayerHandlerServer) error {
	return status.Errorf(codes.Unimplemented, "method PlayerHandler not implemented")
}
func (*UnimplementedPlayerServiceServer) WaitingRoom(PlayerService_WaitingRoomServer) error {
	return status.Errorf(codes.Unimplemented, "method WaitingRoom not implemented")
}
func (*UnimplementedPlayerServiceServer) Fase1P1(PlayerService_Fase1P1Server) error {
	return status.Errorf(codes.Unimplemented, "method Fase1P1 not implemented")
}
func (*UnimplementedPlayerServiceServer) Fase1P2(PlayerService_Fase1P2Server) error {
	return status.Errorf(codes.Unimplemented, "method Fase1P2 not implemented")
}
func (*UnimplementedPlayerServiceServer) Fase2(PlayerService_Fase2Server) error {
	return status.Errorf(codes.Unimplemented, "method Fase2 not implemented")
}
func (*UnimplementedPlayerServiceServer) Fase3(PlayerService_Fase3Server) error {
	return status.Errorf(codes.Unimplemented, "method Fase3 not implemented")
}

func RegisterPlayerServiceServer(s *grpc.Server, srv PlayerServiceServer) {
	s.RegisterService(&_PlayerService_serviceDesc, srv)
}

func _PlayerService_PlayerHandler_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerServiceServer).PlayerHandler(&playerServicePlayerHandlerServer{stream})
}

type PlayerService_PlayerHandlerServer interface {
	Send(*PlayerResponse) error
	Recv() (*PlayerRequest, error)
	grpc.ServerStream
}

type playerServicePlayerHandlerServer struct {
	grpc.ServerStream
}

func (x *playerServicePlayerHandlerServer) Send(m *PlayerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playerServicePlayerHandlerServer) Recv() (*PlayerRequest, error) {
	m := new(PlayerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PlayerService_WaitingRoom_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerServiceServer).WaitingRoom(&playerServiceWaitingRoomServer{stream})
}

type PlayerService_WaitingRoomServer interface {
	Send(*PlayerResponse) error
	Recv() (*PlayerRequest, error)
	grpc.ServerStream
}

type playerServiceWaitingRoomServer struct {
	grpc.ServerStream
}

func (x *playerServiceWaitingRoomServer) Send(m *PlayerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playerServiceWaitingRoomServer) Recv() (*PlayerRequest, error) {
	m := new(PlayerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PlayerService_Fase1P1_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerServiceServer).Fase1P1(&playerServiceFase1P1Server{stream})
}

type PlayerService_Fase1P1Server interface {
	Send(*PlayerResponse) error
	Recv() (*PlayerRequest, error)
	grpc.ServerStream
}

type playerServiceFase1P1Server struct {
	grpc.ServerStream
}

func (x *playerServiceFase1P1Server) Send(m *PlayerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playerServiceFase1P1Server) Recv() (*PlayerRequest, error) {
	m := new(PlayerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PlayerService_Fase1P2_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerServiceServer).Fase1P2(&playerServiceFase1P2Server{stream})
}

type PlayerService_Fase1P2Server interface {
	Send(*PlayerResponse) error
	Recv() (*PlayerRequest, error)
	grpc.ServerStream
}

type playerServiceFase1P2Server struct {
	grpc.ServerStream
}

func (x *playerServiceFase1P2Server) Send(m *PlayerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playerServiceFase1P2Server) Recv() (*PlayerRequest, error) {
	m := new(PlayerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PlayerService_Fase2_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerServiceServer).Fase2(&playerServiceFase2Server{stream})
}

type PlayerService_Fase2Server interface {
	Send(*PlayerResponse) error
	Recv() (*PlayerRequest, error)
	grpc.ServerStream
}

type playerServiceFase2Server struct {
	grpc.ServerStream
}

func (x *playerServiceFase2Server) Send(m *PlayerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playerServiceFase2Server) Recv() (*PlayerRequest, error) {
	m := new(PlayerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PlayerService_Fase3_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerServiceServer).Fase3(&playerServiceFase3Server{stream})
}

type PlayerService_Fase3Server interface {
	Send(*PlayerResponse) error
	Recv() (*PlayerRequest, error)
	grpc.ServerStream
}

type playerServiceFase3Server struct {
	grpc.ServerStream
}

func (x *playerServiceFase3Server) Send(m *PlayerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playerServiceFase3Server) Recv() (*PlayerRequest, error) {
	m := new(PlayerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PlayerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lider.PlayerService",
	HandlerType: (*PlayerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayerHandler",
			Handler:       _PlayerService_PlayerHandler_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WaitingRoom",
			Handler:       _PlayerService_WaitingRoom_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Fase1P1",
			Handler:       _PlayerService_Fase1P1_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Fase1P2",
			Handler:       _PlayerService_Fase1P2_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Fase2",
			Handler:       _PlayerService_Fase2_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Fase3",
			Handler:       _PlayerService_Fase3_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lider.proto",
}
