// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: name.proto

package name

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player  int32   `protobuf:"varint,1,opt,name=player,proto3" json:"player,omitempty"`
	Ronda   int32   `protobuf:"varint,2,opt,name=ronda,proto3" json:"ronda,omitempty"`
	Jugadas []int32 `protobuf:"varint,3,rep,packed,name=jugadas,proto3" json:"jugadas,omitempty"`
}

func (x *NameRequest) Reset() {
	*x = NameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_name_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRequest) ProtoMessage() {}

func (x *NameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_name_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRequest.ProtoReflect.Descriptor instead.
func (*NameRequest) Descriptor() ([]byte, []int) {
	return file_name_proto_rawDescGZIP(), []int{0}
}

func (x *NameRequest) GetPlayer() int32 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *NameRequest) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

func (x *NameRequest) GetJugadas() []int32 {
	if x != nil {
		return x.Jugadas
	}
	return nil
}

type NameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     int32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Response int32   `protobuf:"varint,2,opt,name=response,proto3" json:"response,omitempty"`
	Jugadas  []int32 `protobuf:"varint,3,rep,packed,name=jugadas,proto3" json:"jugadas,omitempty"`
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_name_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_name_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_name_proto_rawDescGZIP(), []int{1}
}

func (x *NameResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *NameResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

func (x *NameResponse) GetJugadas() []int32 {
	if x != nil {
		return x.Jugadas
	}
	return nil
}

var File_name_proto protoreflect.FileDescriptor

var file_name_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x55, 0x0a, 0x0b, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6e,
	0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x22, 0x58, 0x0a, 0x0c, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x73, 0x32, 0x86, 0x01, 0x0a, 0x0b, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72,
	0x12, 0x11, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3d, 0x0a,
	0x0e, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12,
	0x11, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21,
	0x4c, 0x61, 0x62, 0x32, 0x5f, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f,
	0x73, 0x2f, 0x73, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6e, 0x61, 0x6d,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_name_proto_rawDescOnce sync.Once
	file_name_proto_rawDescData = file_name_proto_rawDesc
)

func file_name_proto_rawDescGZIP() []byte {
	file_name_proto_rawDescOnce.Do(func() {
		file_name_proto_rawDescData = protoimpl.X.CompressGZIP(file_name_proto_rawDescData)
	})
	return file_name_proto_rawDescData
}

var file_name_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_name_proto_goTypes = []interface{}{
	(*NameRequest)(nil),  // 0: name.NameRequest
	(*NameResponse)(nil), // 1: name.NameResponse
}
var file_name_proto_depIdxs = []int32{
	0, // 0: name.NameService.Registrar:input_type -> name.NameRequest
	0, // 1: name.NameService.ObtenerJugadas:input_type -> name.NameRequest
	1, // 2: name.NameService.Registrar:output_type -> name.NameResponse
	1, // 3: name.NameService.ObtenerJugadas:output_type -> name.NameResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_name_proto_init() }
func file_name_proto_init() {
	if File_name_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_name_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_name_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_name_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_name_proto_goTypes,
		DependencyIndexes: file_name_proto_depIdxs,
		MessageInfos:      file_name_proto_msgTypes,
	}.Build()
	File_name_proto = out.File
	file_name_proto_rawDesc = nil
	file_name_proto_goTypes = nil
	file_name_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NameServiceClient is the client API for NameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NameServiceClient interface {
	Registrar(ctx context.Context, opts ...grpc.CallOption) (NameService_RegistrarClient, error)
	ObtenerJugadas(ctx context.Context, opts ...grpc.CallOption) (NameService_ObtenerJugadasClient, error)
}

type nameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNameServiceClient(cc grpc.ClientConnInterface) NameServiceClient {
	return &nameServiceClient{cc}
}

func (c *nameServiceClient) Registrar(ctx context.Context, opts ...grpc.CallOption) (NameService_RegistrarClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NameService_serviceDesc.Streams[0], "/name.NameService/Registrar", opts...)
	if err != nil {
		return nil, err
	}
	x := &nameServiceRegistrarClient{stream}
	return x, nil
}

type NameService_RegistrarClient interface {
	Send(*NameRequest) error
	Recv() (*NameResponse, error)
	grpc.ClientStream
}

type nameServiceRegistrarClient struct {
	grpc.ClientStream
}

func (x *nameServiceRegistrarClient) Send(m *NameRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nameServiceRegistrarClient) Recv() (*NameResponse, error) {
	m := new(NameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nameServiceClient) ObtenerJugadas(ctx context.Context, opts ...grpc.CallOption) (NameService_ObtenerJugadasClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NameService_serviceDesc.Streams[1], "/name.NameService/ObtenerJugadas", opts...)
	if err != nil {
		return nil, err
	}
	x := &nameServiceObtenerJugadasClient{stream}
	return x, nil
}

type NameService_ObtenerJugadasClient interface {
	Send(*NameRequest) error
	Recv() (*NameResponse, error)
	grpc.ClientStream
}

type nameServiceObtenerJugadasClient struct {
	grpc.ClientStream
}

func (x *nameServiceObtenerJugadasClient) Send(m *NameRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nameServiceObtenerJugadasClient) Recv() (*NameResponse, error) {
	m := new(NameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NameServiceServer is the server API for NameService service.
type NameServiceServer interface {
	Registrar(NameService_RegistrarServer) error
	ObtenerJugadas(NameService_ObtenerJugadasServer) error
}

// UnimplementedNameServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNameServiceServer struct {
}

func (*UnimplementedNameServiceServer) Registrar(NameService_RegistrarServer) error {
	return status.Errorf(codes.Unimplemented, "method Registrar not implemented")
}
func (*UnimplementedNameServiceServer) ObtenerJugadas(NameService_ObtenerJugadasServer) error {
	return status.Errorf(codes.Unimplemented, "method ObtenerJugadas not implemented")
}

func RegisterNameServiceServer(s *grpc.Server, srv NameServiceServer) {
	s.RegisterService(&_NameService_serviceDesc, srv)
}

func _NameService_Registrar_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NameServiceServer).Registrar(&nameServiceRegistrarServer{stream})
}

type NameService_RegistrarServer interface {
	Send(*NameResponse) error
	Recv() (*NameRequest, error)
	grpc.ServerStream
}

type nameServiceRegistrarServer struct {
	grpc.ServerStream
}

func (x *nameServiceRegistrarServer) Send(m *NameResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nameServiceRegistrarServer) Recv() (*NameRequest, error) {
	m := new(NameRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _NameService_ObtenerJugadas_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NameServiceServer).ObtenerJugadas(&nameServiceObtenerJugadasServer{stream})
}

type NameService_ObtenerJugadasServer interface {
	Send(*NameResponse) error
	Recv() (*NameRequest, error)
	grpc.ServerStream
}

type nameServiceObtenerJugadasServer struct {
	grpc.ServerStream
}

func (x *nameServiceObtenerJugadasServer) Send(m *NameResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nameServiceObtenerJugadasServer) Recv() (*NameRequest, error) {
	m := new(NameRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _NameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "name.NameService",
	HandlerType: (*NameServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Registrar",
			Handler:       _NameService_Registrar_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ObtenerJugadas",
			Handler:       _NameService_ObtenerJugadas_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "name.proto",
}
