// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pozo.proto

package pozo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PozoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Player int32 `protobuf:"varint,2,opt,name=player,proto3" json:"player,omitempty"`
	Ronda  int32 `protobuf:"varint,3,opt,name=ronda,proto3" json:"ronda,omitempty"`
}

func (x *PozoRequest) Reset() {
	*x = PozoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pozo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PozoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PozoRequest) ProtoMessage() {}

func (x *PozoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pozo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PozoRequest.ProtoReflect.Descriptor instead.
func (*PozoRequest) Descriptor() ([]byte, []int) {
	return file_pozo_proto_rawDescGZIP(), []int{0}
}

func (x *PozoRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PozoRequest) GetPlayer() int32 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *PozoRequest) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

type PozoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Response int32 `protobuf:"varint,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *PozoResponse) Reset() {
	*x = PozoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pozo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PozoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PozoResponse) ProtoMessage() {}

func (x *PozoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pozo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PozoResponse.ProtoReflect.Descriptor instead.
func (*PozoResponse) Descriptor() ([]byte, []int) {
	return file_pozo_proto_rawDescGZIP(), []int{1}
}

func (x *PozoResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PozoResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

var File_pozo_proto protoreflect.FileDescriptor

var file_pozo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6f, 0x7a, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x6f,
	0x7a, 0x6f, 0x22, 0x4f, 0x0a, 0x0b, 0x50, 0x6f, 0x7a, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f,
	0x6e, 0x64, 0x61, 0x22, 0x3e, 0x0a, 0x0c, 0x50, 0x6f, 0x7a, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x47, 0x0a, 0x0b, 0x50, 0x6f, 0x7a, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x72, 0x12,
	0x11, 0x2e, 0x70, 0x6f, 0x7a, 0x6f, 0x2e, 0x50, 0x6f, 0x7a, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x6f, 0x7a, 0x6f, 0x2e, 0x50, 0x6f, 0x7a, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21,
	0x4c, 0x61, 0x62, 0x32, 0x5f, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f,
	0x73, 0x2f, 0x73, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x6f, 0x7a,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pozo_proto_rawDescOnce sync.Once
	file_pozo_proto_rawDescData = file_pozo_proto_rawDesc
)

func file_pozo_proto_rawDescGZIP() []byte {
	file_pozo_proto_rawDescOnce.Do(func() {
		file_pozo_proto_rawDescData = protoimpl.X.CompressGZIP(file_pozo_proto_rawDescData)
	})
	return file_pozo_proto_rawDescData
}

var file_pozo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pozo_proto_goTypes = []interface{}{
	(*PozoRequest)(nil),  // 0: pozo.PozoRequest
	(*PozoResponse)(nil), // 1: pozo.PozoResponse
}
var file_pozo_proto_depIdxs = []int32{
	0, // 0: pozo.PozoService.Consultar:input_type -> pozo.PozoRequest
	1, // 1: pozo.PozoService.Consultar:output_type -> pozo.PozoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pozo_proto_init() }
func file_pozo_proto_init() {
	if File_pozo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pozo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PozoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pozo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PozoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pozo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pozo_proto_goTypes,
		DependencyIndexes: file_pozo_proto_depIdxs,
		MessageInfos:      file_pozo_proto_msgTypes,
	}.Build()
	File_pozo_proto = out.File
	file_pozo_proto_rawDesc = nil
	file_pozo_proto_goTypes = nil
	file_pozo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PozoServiceClient is the client API for PozoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PozoServiceClient interface {
	Consultar(ctx context.Context, opts ...grpc.CallOption) (PozoService_ConsultarClient, error)
}

type pozoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPozoServiceClient(cc grpc.ClientConnInterface) PozoServiceClient {
	return &pozoServiceClient{cc}
}

func (c *pozoServiceClient) Consultar(ctx context.Context, opts ...grpc.CallOption) (PozoService_ConsultarClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PozoService_serviceDesc.Streams[0], "/pozo.PozoService/Consultar", opts...)
	if err != nil {
		return nil, err
	}
	x := &pozoServiceConsultarClient{stream}
	return x, nil
}

type PozoService_ConsultarClient interface {
	Send(*PozoRequest) error
	Recv() (*PozoResponse, error)
	grpc.ClientStream
}

type pozoServiceConsultarClient struct {
	grpc.ClientStream
}

func (x *pozoServiceConsultarClient) Send(m *PozoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pozoServiceConsultarClient) Recv() (*PozoResponse, error) {
	m := new(PozoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PozoServiceServer is the server API for PozoService service.
type PozoServiceServer interface {
	Consultar(PozoService_ConsultarServer) error
}

// UnimplementedPozoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPozoServiceServer struct {
}

func (*UnimplementedPozoServiceServer) Consultar(PozoService_ConsultarServer) error {
	return status.Errorf(codes.Unimplemented, "method Consultar not implemented")
}

func RegisterPozoServiceServer(s *grpc.Server, srv PozoServiceServer) {
	s.RegisterService(&_PozoService_serviceDesc, srv)
}

func _PozoService_Consultar_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PozoServiceServer).Consultar(&pozoServiceConsultarServer{stream})
}

type PozoService_ConsultarServer interface {
	Send(*PozoResponse) error
	Recv() (*PozoRequest, error)
	grpc.ServerStream
}

type pozoServiceConsultarServer struct {
	grpc.ServerStream
}

func (x *pozoServiceConsultarServer) Send(m *PozoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pozoServiceConsultarServer) Recv() (*PozoRequest, error) {
	m := new(PozoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PozoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pozo.PozoService",
	HandlerType: (*PozoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consultar",
			Handler:       _PozoService_Consultar_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pozo.proto",
}
