// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: data.proto

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player  int32   `protobuf:"varint,1,opt,name=player,proto3" json:"player,omitempty"`
	Ronda   int32   `protobuf:"varint,2,opt,name=ronda,proto3" json:"ronda,omitempty"`
	Jugadas []int32 `protobuf:"varint,3,rep,packed,name=jugadas,proto3" json:"jugadas,omitempty"`
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetPlayer() int32 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *DataRequest) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

func (x *DataRequest) GetJugadas() []int32 {
	if x != nil {
		return x.Jugadas
	}
	return nil
}

type DataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     int32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Response int32   `protobuf:"varint,2,opt,name=response,proto3" json:"response,omitempty"`
	Jugadas  []int32 `protobuf:"varint,3,rep,packed,name=jugadas,proto3" json:"jugadas,omitempty"`
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *DataResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DataResponse) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

func (x *DataResponse) GetJugadas() []int32 {
	if x != nil {
		return x.Jugadas
	}
	return nil
}

var File_data_proto protoreflect.FileDescriptor

var file_data_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x55, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6e,
	0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x22, 0x58, 0x0a, 0x0c, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x73, 0x32, 0x8d, 0x01, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72,
	0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x12, 0x3d, 0x0a, 0x0e, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4a,
	0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x4c, 0x61, 0x62, 0x32, 0x5f, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f, 0x73, 0x2f, 0x73, 0x71, 0x75, 0x69, 0x64, 0x5f, 0x67,
	0x61, 0x6d, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData = file_data_proto_rawDesc
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_proto_rawDescData)
	})
	return file_data_proto_rawDescData
}

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_proto_goTypes = []interface{}{
	(*DataRequest)(nil),  // 0: data.DataRequest
	(*DataResponse)(nil), // 1: data.DataResponse
}
var file_data_proto_depIdxs = []int32{
	0, // 0: data.DataService.RegistrarJugadas:input_type -> data.DataRequest
	0, // 1: data.DataService.ObtenerJugadas:input_type -> data.DataRequest
	1, // 2: data.DataService.RegistrarJugadas:output_type -> data.DataResponse
	1, // 3: data.DataService.ObtenerJugadas:output_type -> data.DataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_rawDesc = nil
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataServiceClient interface {
	RegistrarJugadas(ctx context.Context, opts ...grpc.CallOption) (DataService_RegistrarJugadasClient, error)
	ObtenerJugadas(ctx context.Context, opts ...grpc.CallOption) (DataService_ObtenerJugadasClient, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) RegistrarJugadas(ctx context.Context, opts ...grpc.CallOption) (DataService_RegistrarJugadasClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataService_serviceDesc.Streams[0], "/data.DataService/RegistrarJugadas", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataServiceRegistrarJugadasClient{stream}
	return x, nil
}

type DataService_RegistrarJugadasClient interface {
	Send(*DataRequest) error
	Recv() (*DataResponse, error)
	grpc.ClientStream
}

type dataServiceRegistrarJugadasClient struct {
	grpc.ClientStream
}

func (x *dataServiceRegistrarJugadasClient) Send(m *DataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataServiceRegistrarJugadasClient) Recv() (*DataResponse, error) {
	m := new(DataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataServiceClient) ObtenerJugadas(ctx context.Context, opts ...grpc.CallOption) (DataService_ObtenerJugadasClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataService_serviceDesc.Streams[1], "/data.DataService/ObtenerJugadas", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataServiceObtenerJugadasClient{stream}
	return x, nil
}

type DataService_ObtenerJugadasClient interface {
	Send(*DataRequest) error
	Recv() (*DataResponse, error)
	grpc.ClientStream
}

type dataServiceObtenerJugadasClient struct {
	grpc.ClientStream
}

func (x *dataServiceObtenerJugadasClient) Send(m *DataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataServiceObtenerJugadasClient) Recv() (*DataResponse, error) {
	m := new(DataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataServiceServer is the server API for DataService service.
type DataServiceServer interface {
	RegistrarJugadas(DataService_RegistrarJugadasServer) error
	ObtenerJugadas(DataService_ObtenerJugadasServer) error
}

// UnimplementedDataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (*UnimplementedDataServiceServer) RegistrarJugadas(DataService_RegistrarJugadasServer) error {
	return status.Errorf(codes.Unimplemented, "method RegistrarJugadas not implemented")
}
func (*UnimplementedDataServiceServer) ObtenerJugadas(DataService_ObtenerJugadasServer) error {
	return status.Errorf(codes.Unimplemented, "method ObtenerJugadas not implemented")
}

func RegisterDataServiceServer(s *grpc.Server, srv DataServiceServer) {
	s.RegisterService(&_DataService_serviceDesc, srv)
}

func _DataService_RegistrarJugadas_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServiceServer).RegistrarJugadas(&dataServiceRegistrarJugadasServer{stream})
}

type DataService_RegistrarJugadasServer interface {
	Send(*DataResponse) error
	Recv() (*DataRequest, error)
	grpc.ServerStream
}

type dataServiceRegistrarJugadasServer struct {
	grpc.ServerStream
}

func (x *dataServiceRegistrarJugadasServer) Send(m *DataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataServiceRegistrarJugadasServer) Recv() (*DataRequest, error) {
	m := new(DataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DataService_ObtenerJugadas_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServiceServer).ObtenerJugadas(&dataServiceObtenerJugadasServer{stream})
}

type DataService_ObtenerJugadasServer interface {
	Send(*DataResponse) error
	Recv() (*DataRequest, error)
	grpc.ServerStream
}

type dataServiceObtenerJugadasServer struct {
	grpc.ServerStream
}

func (x *dataServiceObtenerJugadasServer) Send(m *DataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataServiceObtenerJugadasServer) Recv() (*DataRequest, error) {
	m := new(DataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegistrarJugadas",
			Handler:       _DataService_RegistrarJugadas_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ObtenerJugadas",
			Handler:       _DataService_ObtenerJugadas_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "data.proto",
}
